kind: pipeline
type: docker
name: default
when:
  event: [ push ]
  branch: [ main ]

steps:
  - name: build
    image: alpine/edge
    commands:
      - apk update && apk add --no-cache hugo
      - hugo
