kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: alpine:edge
    commands:
      - apk update && apk add --no-cache hugo
      - hugo

  - name: deploy
    image: alpine:edge
    environment:
      SSH_KEY:
        from_secret: ssh_key
      USERNAME:
        fron_secret: username
      PORT:
        from_secret: port
      HOST:
        from_secret: host
      DEPLOY_PATH:
        from_secret: deploy_path
    commands:
      - apk update && apk add --no-cache ca-certificates bash openssh-client rsync
      - |
        mkdir ~/.ssh/
        echo "StrictHostKeyChecking=no" >> ~/.ssh/config
        echo ${SSH_KEY} > ~/.ssh/key
      - rsync -rP -e "ssh -p ${PORT} -i ~/.ssh/key" public/ ${USERNAME}@${HOST}:${DEPLOY_PATH}
