---
baseurl: "https://mornie.org/"
title: "Daniele 'eriol' Tricoli Website"
languageCode: en-us
MetaDataFormat: yaml
pluralizeListTitles: false
author:
    name: "Daniele Tricoli"
permalinks:
    blog: /blog/:year/:month/:day/:filename/
taxonomies:
  tag: "tags"
  category: "categories"
---
