---
baseurl: "https://mornie.org/"
title: "Daniele 'Eriol' Tricoli Website"
languageCode: en-us
MetaDataFormat: yaml
pluralizeListTitles: false
permalinks:
    blog: /blog/:year/:month/:day/:filename/
---
