base_url = "https://mornie.org"
title = "Daniele 'eriol' Tricoli Website"
compile_sass = true
build_search_index = false
generate_feed = true
taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true}
]

[markdown]
highlight_code = true
highlight_theme = "monokai"

[extra]
author = "Daniele Tricoli"
domain = "mornie.org"
