---
baseurl: "https://mornie.org/"
title: "Daniele 'Eriol' Tricoli Website"
languageCode: en-us
MetaDataFormat: yaml
pluralizeListTitles: false
disqusShortname: mornie
permalinks:
    blog: /blog/:year/:month/:day/:filename/
taxonomies:
  tag: "tags"
  category: "categories"
---
