---

when:
  - branch: main

steps:

  - build:
    image: alpine:edge
    commands:
      - apk update && apk add --no-cache zola
      - zola build

  - deploy:
    image: alpine:edge
    commands:
      - apk update && apk add --no-cache ca-certificates bash openssh-client rsync
      - |
        mkdir ~/.ssh/
        echo -e "StrictHostKeyChecking=no\nUserKnownHostsFile=/dev/null" >> ~/.ssh/config
        chmod 0700 ~/.ssh/config
        echo "$SSH_KEY" > ~/.ssh/key
        chmod 0600 ~/.ssh/key
      - rsync -rP --delete -e "ssh -p $PORT -i ~/.ssh/key" public/ "$USERNAME@$HOST:$DEPLOY_PATH"
    secrets: [ssh_key, username, port, host, deploy_path]
