---
name: Build an publish on mornie.org

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:edge
    steps:
      - uses: actions/checkout@v4
      - name: Create cache for files to deploy
        uses: actions/cache@v4
        with:
          path: public
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - run: apk update && apk add --no-cache zola
      - run: zola build
      - run: ls

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install ca-certificates bash openssh-client rsync
      - run: |
          mkdir ~/.ssh/
          echo -e "StrictHostKeyChecking=no\nUserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 0700 ~/.ssh/config
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/key
          chmod 0600 ~/.ssh/key
      - run: ls
      - name: Restore cached file to deploy
        uses: actions/cache/restore@v4
        with:
          path: public
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - run: rsync -rP --delete -e "ssh -p ${{secrets.PORT}} -i ~/.ssh/key" public/ "${{secrets.USERNAME}}@${{secrets.HOST}}:${{secrets.DEPLOY_PATH}}"
