---
name: Build an publish on mornie.org

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container: alpine:edge
    steps:
      - uses: actions/checkout@v4
      - run: apk update && apk add --no-cache zola
      - run: zola build
