---
name: Build an publish on mornie.org

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install zola and build the site
        run: |
          sudo stap install --edge zola
          zola build
      - name: Create cache for files to deploy
        uses: actions/cache/save@v4
        with:
          path: |
            public
          key: ${{ runner.os }}-zola-${{ github.sha }}

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install ca-certificates bash openssh-client rsync
      - run: |
          mkdir ~/.ssh/
          echo -e "StrictHostKeyChecking=no\nUserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 0700 ~/.ssh/config
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/key
          chmod 0600 ~/.ssh/key
      - name: Restore cached file to deploy
        uses: actions/cache/restore@v4
        with:
          path: |
            public
          key: ${{ runner.os }}-zola-${{ github.sha }}
      - run: ls
      - run: rsync -rP --delete -e "ssh -p ${{secrets.PORT}} -i ~/.ssh/key" public/ "${{secrets.USERNAME}}@${{secrets.HOST}}:${{secrets.DEPLOY_PATH}}"
